# Generated by Django 5.0.6 on 2024-06-09 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories_images', verbose_name='image')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('barcode', models.IntegerField(verbose_name='barcode')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('provider', models.CharField(blank=True, max_length=128, verbose_name='provider')),
                ('price', models.FloatField(verbose_name='price')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='craete_time')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='image')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces')], max_length=128, verbose_name='unit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kassaApi.category', verbose_name='category')),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
    ]
